data:
  gpu: 0
  num_workers: 1
  train_dataset: data/NICO/
  dataset_name: nico_plus_plus_super_95
  num_classes: 6
training:
  arch: resnet50
  batch_size: 64
  steps: 25000
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1.0
  lr_tta: false
  num_workers: 6
  save_dir: outputs/nico_plus_plus/
  eval_freq: -1
  exp_name: amco_95
  pretrained: True
  n_trials: 1
  seed: 0